<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWACMvm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWACMvm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWWACMvm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWWACMvm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWWACMvm\App_KernelDevDebugContainer([
    'container.build_hash' => 'WWACMvm',
    'container.build_id' => 'eb4f50a7',
    'container.build_time' => 1641820590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWACMvm');
