<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZtASepI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZtASepI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZtASepI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZtASepI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZtASepI\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZtASepI',
    'container.build_id' => '7d4a717d',
    'container.build_time' => 1641806244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZtASepI');
