<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAGy8UF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAGy8UF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAGy8UF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAGy8UF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAGy8UF\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAGy8UF',
    'container.build_id' => '298d6d1c',
    'container.build_time' => 1641903714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAGy8UF');
